# docker.yml - Docker installation
#
# Usage:
#   ansible-playbook docker.yml -i "localhost," -c local --ask-become-pass
#
# For NVIDIA GPU support, also run nvidia-container-toolkit.yml then:
#   sudo nvidia-ctk runtime configure --runtime=docker
#   sudo systemctl restart docker
---
- name: Install Docker
  hosts: all
  become: yes
  vars:
    docker_user: "{{ ansible_user_id }}"

  tasks:
    - name: Install Docker using convenience script
      shell: |
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
