# gpu-servers.yml - GPU server setup with NVIDIA drivers and tools
#
# Usage:
#   Run all:        ansible-playbook gpu-servers.yml -i "localhost," -c local --ask-become-pass
#   Run by tag:     ansible-playbook gpu-servers.yml -i "localhost," -c local --tags gcloud --ask-become-pass
#
# Available tags: prereqs, nvidia-drivers, cuda, reboot
#
# Note: For Docker + NVIDIA runtime, use docker-nvidia.yml
---
- name: Configure GPU Servers
  hosts: all
  become: yes

  tasks:
    # ===================
    # Prerequisites
    # ===================
    - name: Install prerequisites
      tags: prereqs
      apt:
        name:
          - build-essential
          - linux-headers-generic
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - just
          - unzip
        state: present
        update_cache: yes

    # ===================
    # NVIDIA Drivers
    # ===================
    - name: Install NVIDIA drivers
      tags: nvidia-drivers
      apt:
        name:
          - nvidia-driver-550
          - nvidia-utils-550
        state: present

    # ===================
    # CUDA Toolkit
    # ===================
    - block:
        - name: Install NVCC and CUDA toolkit
          apt:
            name:
              - python3-dev
              - nvidia-cuda-toolkit
            state: present
            update_cache: yes
      tags: cuda

    # ===================
    # Reboot
    # ===================
    - name: Reboot system
      tags: [reboot, never]
      reboot:
        reboot_timeout: 300
