# nvidia-container-toolkit.yml - NVIDIA Container Toolkit (works with Docker or Podman)
#
# Usage:
#   ansible-playbook nvidia-container-toolkit.yml -i "localhost," -c local --ask-become-pass
#
# After install, configure your runtime:
#   Docker:  sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker
#   Podman:  sudo nvidia-ctk runtime configure --runtime=podman
#   Containerd: sudo nvidia-ctk runtime configure --runtime=containerd && sudo systemctl restart containerd
---
- name: Install NVIDIA Container Toolkit
  hosts: all
  become: yes

  tasks:
    - name: Add NVIDIA Container Toolkit GPG key
      shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
        gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA Container Toolkit repository
      shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present
        update_cache: yes
